### ISSUE TITLE
[FEATURE-REQ] Digital clock option

### ISSUE THREAD

**Issue by SesioN** [Nxt3/IO_Classic_WatchFace#6]
While it is possible to set a digial clock via complications, doing it so is very limited. 

Eg. only clock + date, or only date (via google clock complication), no color or size settings

So adding dedicated digal clock option, where you can set the position, size, font and color would be awesome!

**Comment by Nxt3** [comment]
I don't have plans to do this. This watch face is an analog watch face first and foremost. If I decided to do this, it would be with a new watchface--not a setting to this one.
