### ISSUE TITLE
[FEATURE-REQ] Additonal settings for ticks

### ISSUE THREAD

**Issue by SesioN** [Nxt3/IO_Classic_WatchFace#8]
1) Allow choosing whenever you want a line passing thru all ticks or have just the the tick lines themself displayed

2) Option to set if you want a thick tick line for each hour, 6, 12 hours etc.

3) Option to set color for thick lines

**Comment by Nxt3** [comment]
Personally, I feel like there are already too many settings with this. It would further complicate the already bloated settings page. 

Not to mention this would actually take a fair amount of code changes; there would be a lot of `if-else` statements checking to see which colors to draw things. 

Honestly, it sounds like you want something like Watchmaker or Pujie Black; sorry if that sounds rude, but it's more involved to add all of your feature requests than if you just made your own watchface with an already available app.
